apiVersion: v1
kind: Service
metadata:
  name: tpfoyer-service
  labels:
    app: tpfoyer
spec:
  type: NodePort
  selector:
    app: tpfoyer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080